// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// phm_fixed_a0
Rcpp::List phm_fixed_a0(Rcpp::List& curr_tables0, Rcpp::List& hist_tables0, arma::vec& a0_vec0, arma::vec& n_intervals0, bool& shared_blh0, int P0, std::string prior_beta0, arma::vec prior_beta_mu0, arma::vec prior_beta_sigma0, std::string prior_lambda0, arma::vec prior_lambda_hp10, arma::vec prior_lambda_hp20, arma::vec prior_lambdah_hp10, arma::vec prior_lambdah_hp20, arma::vec& lower_limits0, arma::vec& upper_limits0, arma::vec& slice_widths0, int nMC, int nBI, bool& dCurrent0);
RcppExport SEXP _BayesPPDSurv_phm_fixed_a0(SEXP curr_tables0SEXP, SEXP hist_tables0SEXP, SEXP a0_vec0SEXP, SEXP n_intervals0SEXP, SEXP shared_blh0SEXP, SEXP P0SEXP, SEXP prior_beta0SEXP, SEXP prior_beta_mu0SEXP, SEXP prior_beta_sigma0SEXP, SEXP prior_lambda0SEXP, SEXP prior_lambda_hp10SEXP, SEXP prior_lambda_hp20SEXP, SEXP prior_lambdah_hp10SEXP, SEXP prior_lambdah_hp20SEXP, SEXP lower_limits0SEXP, SEXP upper_limits0SEXP, SEXP slice_widths0SEXP, SEXP nMCSEXP, SEXP nBISEXP, SEXP dCurrent0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type curr_tables0(curr_tables0SEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type hist_tables0(hist_tables0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type a0_vec0(a0_vec0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type n_intervals0(n_intervals0SEXP);
    Rcpp::traits::input_parameter< bool& >::type shared_blh0(shared_blh0SEXP);
    Rcpp::traits::input_parameter< int >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< std::string >::type prior_beta0(prior_beta0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_beta_mu0(prior_beta_mu0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_beta_sigma0(prior_beta_sigma0SEXP);
    Rcpp::traits::input_parameter< std::string >::type prior_lambda0(prior_lambda0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_lambda_hp10(prior_lambda_hp10SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_lambda_hp20(prior_lambda_hp20SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_lambdah_hp10(prior_lambdah_hp10SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_lambdah_hp20(prior_lambdah_hp20SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type lower_limits0(lower_limits0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type upper_limits0(upper_limits0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type slice_widths0(slice_widths0SEXP);
    Rcpp::traits::input_parameter< int >::type nMC(nMCSEXP);
    Rcpp::traits::input_parameter< int >::type nBI(nBISEXP);
    Rcpp::traits::input_parameter< bool& >::type dCurrent0(dCurrent0SEXP);
    rcpp_result_gen = Rcpp::wrap(phm_fixed_a0(curr_tables0, hist_tables0, a0_vec0, n_intervals0, shared_blh0, P0, prior_beta0, prior_beta_mu0, prior_beta_sigma0, prior_lambda0, prior_lambda_hp10, prior_lambda_hp20, prior_lambdah_hp10, prior_lambdah_hp20, lower_limits0, upper_limits0, slice_widths0, nMC, nBI, dCurrent0));
    return rcpp_result_gen;
END_RCPP
}
// phm_random_a0
Rcpp::List phm_random_a0(Rcpp::List& curr_tables0, Rcpp::List& hist_tables0, arma::vec& n_intervals0, int P0, Rcpp::List& prior_beta_mvn0, arma::vec prior_lambda_hp10, arma::vec prior_lambda_hp20, arma::vec& lower_limits0, arma::vec& upper_limits0, arma::vec& slice_widths0, int nMC, int nBI);
RcppExport SEXP _BayesPPDSurv_phm_random_a0(SEXP curr_tables0SEXP, SEXP hist_tables0SEXP, SEXP n_intervals0SEXP, SEXP P0SEXP, SEXP prior_beta_mvn0SEXP, SEXP prior_lambda_hp10SEXP, SEXP prior_lambda_hp20SEXP, SEXP lower_limits0SEXP, SEXP upper_limits0SEXP, SEXP slice_widths0SEXP, SEXP nMCSEXP, SEXP nBISEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type curr_tables0(curr_tables0SEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type hist_tables0(hist_tables0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type n_intervals0(n_intervals0SEXP);
    Rcpp::traits::input_parameter< int >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type prior_beta_mvn0(prior_beta_mvn0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_lambda_hp10(prior_lambda_hp10SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_lambda_hp20(prior_lambda_hp20SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type lower_limits0(lower_limits0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type upper_limits0(upper_limits0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type slice_widths0(slice_widths0SEXP);
    Rcpp::traits::input_parameter< int >::type nMC(nMCSEXP);
    Rcpp::traits::input_parameter< int >::type nBI(nBISEXP);
    rcpp_result_gen = Rcpp::wrap(phm_random_a0(curr_tables0, hist_tables0, n_intervals0, P0, prior_beta_mvn0, prior_lambda_hp10, prior_lambda_hp20, lower_limits0, upper_limits0, slice_widths0, nMC, nBI));
    return rcpp_result_gen;
END_RCPP
}
// npp_beta
Rcpp::List npp_beta(int L, Rcpp::List& hist_tables0, arma::vec& n_intervals0, int P0, arma::vec prior_a0_shape1, arma::vec prior_a0_shape2, arma::vec prior_beta_mu0, arma::vec prior_beta_sigma0, arma::vec prior_lambdah_hp10, arma::vec prior_lambdah_hp20, arma::vec& lower_limits0, arma::vec& upper_limits0, arma::vec& slice_widths0, int nBI);
RcppExport SEXP _BayesPPDSurv_npp_beta(SEXP LSEXP, SEXP hist_tables0SEXP, SEXP n_intervals0SEXP, SEXP P0SEXP, SEXP prior_a0_shape1SEXP, SEXP prior_a0_shape2SEXP, SEXP prior_beta_mu0SEXP, SEXP prior_beta_sigma0SEXP, SEXP prior_lambdah_hp10SEXP, SEXP prior_lambdah_hp20SEXP, SEXP lower_limits0SEXP, SEXP upper_limits0SEXP, SEXP slice_widths0SEXP, SEXP nBISEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type hist_tables0(hist_tables0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type n_intervals0(n_intervals0SEXP);
    Rcpp::traits::input_parameter< int >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_a0_shape1(prior_a0_shape1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_a0_shape2(prior_a0_shape2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_beta_mu0(prior_beta_mu0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_beta_sigma0(prior_beta_sigma0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_lambdah_hp10(prior_lambdah_hp10SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_lambdah_hp20(prior_lambdah_hp20SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type lower_limits0(lower_limits0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type upper_limits0(upper_limits0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type slice_widths0(slice_widths0SEXP);
    Rcpp::traits::input_parameter< int >::type nBI(nBISEXP);
    rcpp_result_gen = Rcpp::wrap(npp_beta(L, hist_tables0, n_intervals0, P0, prior_a0_shape1, prior_a0_shape2, prior_beta_mu0, prior_beta_sigma0, prior_lambdah_hp10, prior_lambdah_hp20, lower_limits0, upper_limits0, slice_widths0, nBI));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesPPDSurv_phm_fixed_a0", (DL_FUNC) &_BayesPPDSurv_phm_fixed_a0, 20},
    {"_BayesPPDSurv_phm_random_a0", (DL_FUNC) &_BayesPPDSurv_phm_random_a0, 12},
    {"_BayesPPDSurv_npp_beta", (DL_FUNC) &_BayesPPDSurv_npp_beta, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesPPDSurv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
