# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

phm_fixed_a0 <- function(curr_tables0, hist_tables0, a0_vec0, n_intervals0, shared_blh0, P0, prior_beta0, prior_beta_mu0, prior_beta_sigma0, prior_lambda0, prior_lambda_hp10, prior_lambda_hp20, prior_lambdah_hp10, prior_lambdah_hp20, lower_limits0, upper_limits0, slice_widths0, nMC, nBI, dCurrent0) {
    .Call(`_BayesPPDSurv_phm_fixed_a0`, curr_tables0, hist_tables0, a0_vec0, n_intervals0, shared_blh0, P0, prior_beta0, prior_beta_mu0, prior_beta_sigma0, prior_lambda0, prior_lambda_hp10, prior_lambda_hp20, prior_lambdah_hp10, prior_lambdah_hp20, lower_limits0, upper_limits0, slice_widths0, nMC, nBI, dCurrent0)
}

phm_random_a0 <- function(curr_tables0, hist_tables0, n_intervals0, P0, prior_beta_mvn0, prior_lambda_hp10, prior_lambda_hp20, lower_limits0, upper_limits0, slice_widths0, nMC, nBI) {
    .Call(`_BayesPPDSurv_phm_random_a0`, curr_tables0, hist_tables0, n_intervals0, P0, prior_beta_mvn0, prior_lambda_hp10, prior_lambda_hp20, lower_limits0, upper_limits0, slice_widths0, nMC, nBI)
}

npp_beta <- function(L, hist_tables0, n_intervals0, P0, prior_a0_shape1, prior_a0_shape2, prior_beta_mu0, prior_beta_sigma0, prior_lambdah_hp10, prior_lambdah_hp20, lower_limits0, upper_limits0, slice_widths0, nBI) {
    .Call(`_BayesPPDSurv_npp_beta`, L, hist_tables0, n_intervals0, P0, prior_a0_shape1, prior_a0_shape2, prior_beta_mu0, prior_beta_sigma0, prior_lambdah_hp10, prior_lambdah_hp20, lower_limits0, upper_limits0, slice_widths0, nBI)
}

